AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Options API Service on ECS

Parameters:
  ECRImageURI:
    Type: String
    Description: URI for the ECR Docker image
  CertificateArn:
    Type: String
    Description: The ARN of the SSL/TLS certificate from AWS Certificate Manager
  ALBArn:
    Type: String
    Description: The ARN of the existing Application Load Balancer
  HTTPListenerArn:
    Type: String
    Description: The ARN of the existing HTTP Listener
  HTTPSListenerArn:
    Type: String
    Description: The ARN of the existing HTTPS Listener
  ECSClusterName:
    Type: String
    Description: The name of the existing ECS Cluster
  PublicSubnetOne:
    Type: String
    Description: The ID of the first public subnet
  PublicSubnetTwo:
    Type: String
    Description: The ID of the second public subnet
  SecurityGroup:
    Type: String
    Description: The ID of the security group
  VpcId:
    Type: String
    Description: The ID of the VPC
  ECSTaskExecutionRoleArn:
    Type: String
    Description: The ARN of the ECS Task Execution Role

Resources:
  OptionsApiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: options-api-tg
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckPath: "/"
      HealthCheckProtocol: HTTP
      HealthCheckPort: "8080"

  OptionsApiHTTPListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref OptionsApiTargetGroup
      Conditions:
        - Field: host-header
          Values: ["api.jrdub.com"]
      ListenerArn: !Ref HTTPListenerArn
      Priority: 1

  OptionsApiHTTPSListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref OptionsApiTargetGroup
      Conditions:
        - Field: host-header
          Values: ["api.jrdub.com"]
      ListenerArn: !Ref HTTPSListenerArn
      Priority: 1

  OptionsApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: options-api-td
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      ContainerDefinitions:
        - Name: options-api-container
          Image: !Ref ECRImageURI
          Essential: true
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/options-api
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs            
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

  OptionsApiECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: options-api-service
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref OptionsApiTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: options-api-container
          ContainerPort: 8080
          TargetGroupArn: !Ref OptionsApiTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PublicSubnetOne
            - !Ref PublicSubnetTwo
          SecurityGroups:
            - !Ref SecurityGroup
          AssignPublicIp: ENABLED

Outputs:
  OptionsApiALBDNSName:
    Description: "The DNS Name of the ALB"
    Value: !Ref ALBArn
